# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfazProyecto.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
from drawnow import *
from lectura import Lectura
from escritura import Escritura
from graficador import Grafica

LIM = 100


class Ui_mainWindow(object):
    def accionesBotones(self):
        return

    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1054, 622)
        mainWindow.setStyleSheet("background-color: rgb(107, 107, 107);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 70, 491, 411))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.grupoConfiguracion = QtWidgets.QGroupBox(self.centralwidget)
        self.grupoConfiguracion.setGeometry(QtCore.QRect(510, 430, 531, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grupoConfiguracion.setFont(font)
        self.grupoConfiguracion.setStyleSheet("color: rgb(241, 241, 241);")
        self.grupoConfiguracion.setObjectName("grupoConfiguracion")
        self.lbl_puerto = QtWidgets.QLabel(self.grupoConfiguracion)
        self.lbl_puerto.setGeometry(QtCore.QRect(20, 30, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_puerto.setFont(font)
        self.lbl_puerto.setObjectName("lbl_puerto")
        self.txt_puerto = QtWidgets.QTextEdit(self.grupoConfiguracion)
        self.txt_puerto.setGeometry(QtCore.QRect(70, 30, 111, 41))
        self.txt_puerto.setObjectName("txt_puerto")
        self.lbl_archivo = QtWidgets.QLabel(self.grupoConfiguracion)
        self.lbl_archivo.setGeometry(QtCore.QRect(190, 30, 61, 16))
        self.lbl_archivo.setObjectName("lbl_archivo")
        self.txt_archivo = QtWidgets.QTextEdit(self.grupoConfiguracion)
        self.txt_archivo.setGeometry(QtCore.QRect(250, 30, 271, 41))
        self.txt_archivo.setObjectName("txt_archivo")
        self.grupoIndicadores = QtWidgets.QGroupBox(self.centralwidget)
        self.grupoIndicadores.setGeometry(QtCore.QRect(550, 80, 431, 311))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grupoIndicadores.setFont(font)
        self.grupoIndicadores.setStyleSheet("color: rgb(243, 243, 243);")
        self.grupoIndicadores.setObjectName("grupoIndicadores")
        self.lbl_bpm = QtWidgets.QLabel(self.grupoIndicadores)
        self.lbl_bpm.setGeometry(QtCore.QRect(90, 30, 47, 13))
        self.lbl_bpm.setObjectName("lbl_bpm")
        self.lbl_ibi = QtWidgets.QLabel(self.grupoIndicadores)
        self.lbl_ibi.setGeometry(QtCore.QRect(90, 70, 47, 13))
        self.lbl_ibi.setObjectName("lbl_ibi")
        self.lbl_sdnn = QtWidgets.QLabel(self.grupoIndicadores)
        self.lbl_sdnn.setGeometry(QtCore.QRect(90, 110, 47, 13))
        self.lbl_sdnn.setObjectName("lbl_sdnn")
        self.lbl_sdsd = QtWidgets.QLabel(self.grupoIndicadores)
        self.lbl_sdsd.setGeometry(QtCore.QRect(90, 150, 47, 13))
        self.lbl_sdsd.setObjectName("lbl_sdsd")
        self.lbl_rmssd = QtWidgets.QLabel(self.grupoIndicadores)
        self.lbl_rmssd.setGeometry(QtCore.QRect(90, 190, 61, 16))
        self.lbl_rmssd.setObjectName("lbl_rmssd")
        self.lbl_pnn20 = QtWidgets.QLabel(self.grupoIndicadores)
        self.lbl_pnn20.setGeometry(QtCore.QRect(90, 230, 61, 16))
        self.lbl_pnn20.setObjectName("lbl_pnn20")
        self.lbl_pnn50 = QtWidgets.QLabel(self.grupoIndicadores)
        self.lbl_pnn50.setGeometry(QtCore.QRect(90, 270, 61, 16))
        self.lbl_pnn50.setObjectName("lbl_pnn50")
        self.txt_bpm = QtWidgets.QTextEdit(self.grupoIndicadores)
        self.txt_bpm.setEnabled(False)
        self.txt_bpm.setGeometry(QtCore.QRect(150, 30, 181, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.txt_bpm.setFont(font)
        self.txt_bpm.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_bpm.setObjectName("txt_bpm")
        self.txt_ibi = QtWidgets.QTextEdit(self.grupoIndicadores)
        self.txt_ibi.setEnabled(False)
        self.txt_ibi.setGeometry(QtCore.QRect(150, 70, 181, 31))
        self.txt_ibi.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_ibi.setObjectName("txt_ibi")
        self.txt_sdnn = QtWidgets.QTextEdit(self.grupoIndicadores)
        self.txt_sdnn.setEnabled(False)
        self.txt_sdnn.setGeometry(QtCore.QRect(150, 110, 181, 31))
        self.txt_sdnn.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_sdnn.setObjectName("txt_sdnn")
        self.txt_sdsd = QtWidgets.QTextEdit(self.grupoIndicadores)
        self.txt_sdsd.setEnabled(False)
        self.txt_sdsd.setGeometry(QtCore.QRect(150, 150, 181, 31))
        self.txt_sdsd.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_sdsd.setObjectName("txt_sdsd")
        self.txt_rmssd = QtWidgets.QTextEdit(self.grupoIndicadores)
        self.txt_rmssd.setEnabled(False)
        self.txt_rmssd.setGeometry(QtCore.QRect(150, 190, 181, 31))
        self.txt_rmssd.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_rmssd.setObjectName("txt_rmssd")
        self.txt_pnn20 = QtWidgets.QTextEdit(self.grupoIndicadores)
        self.txt_pnn20.setEnabled(False)
        self.txt_pnn20.setGeometry(QtCore.QRect(150, 230, 181, 31))
        self.txt_pnn20.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_pnn20.setObjectName("txt_pnn20")
        self.txt_pnn50 = QtWidgets.QTextEdit(self.grupoIndicadores)
        self.txt_pnn50.setEnabled(False)
        self.txt_pnn50.setGeometry(QtCore.QRect(150, 270, 181, 31))
        self.txt_pnn50.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_pnn50.setObjectName("txt_pnn50")
        self.numero_BPM = QtWidgets.QLCDNumber(self.grupoIndicadores)
        self.numero_BPM.setGeometry(QtCore.QRect(340, 30, 81, 31))
        self.numero_BPM.setProperty("intValue", 7866)
        self.numero_BPM.setObjectName("numero_BPM")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 550, 131, 41))
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 550, 131, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(214, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lbl_titulo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_titulo.setGeometry(QtCore.QRect(10, 10, 1031, 31))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setStyleSheet("color: rgb(239, 239, 239);")
        self.lbl_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulo.setObjectName("lbl_titulo")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

        self.accionesBotones()
        return

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Monitor de Frecuencia Cardiaca"))
        self.grupoConfiguracion.setTitle(_translate("mainWindow", "Configuracion"))
        self.lbl_puerto.setText(_translate("mainWindow", "Puerto:"))
        self.txt_puerto.setPlaceholderText(_translate("mainWindow", "COM5"))
        self.lbl_archivo.setText(_translate("mainWindow", "Archivo:"))
        self.txt_archivo.setPlaceholderText(_translate("mainWindow", "nombreArchivo.csv"))
        self.grupoIndicadores.setTitle(_translate("mainWindow", "Indicadores"))
        self.lbl_bpm.setText(_translate("mainWindow", "BPM:"))
        self.lbl_ibi.setText(_translate("mainWindow", "IBI:"))
        self.lbl_sdnn.setText(_translate("mainWindow", "SDNN: "))
        self.lbl_sdsd.setText(_translate("mainWindow", "SDSD:"))
        self.lbl_rmssd.setText(_translate("mainWindow", "RMSSD:"))
        self.lbl_pnn20.setText(_translate("mainWindow", "PNN20:"))
        self.lbl_pnn50.setText(_translate("mainWindow", "PNN50:"))
        self.txt_bpm.setHtml(_translate("mainWindow",
                                        "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:italic;\">\n"
                                        "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("mainWindow", "Iniciar Lecturas"))
        self.pushButton_2.setText(_translate("mainWindow", "Detener Lecturas"))
        self.lbl_titulo.setText(_translate("mainWindow", "Monitor de frecuencia cardiaca"))
        return
